dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: jx-demo-microservice
  repository: http://jenkins-x-chartmuseum:8080
  version: 2.0.8
- name: jx-demo-microservice2
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: subscription
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
